# Generated by Django 5.0.1 on 2024-01-11 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Normal'), (4, 'Good'), (2, 'Bad'), (5, 'Excellent'), (1, 'Too bad')]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'product')},
        ),
    ]
