# Generated by Django 5.0.1 on 2024-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_rating_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (1, 'Too bad'), (3, 'Normal'), (4, 'Good'), (2, 'Bad')]),
        ),
    ]
